dependency:
  name: galaxy
driver:
  name: docker
lint:
  ansible-lint .
  yamllint .
platforms:
  - name: centos8
    image: centos:8
    pre_build_image: true
  - name: centos7
    image: centos:7
    pre_build_imagr: true
  - name: ubuntu_latest
    image: ubuntu:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
