dependency:
  name: galaxy
driver:
  name: docker
lint:
  ansible-lint .
  yamllint .
platforms:
  - name: centos8
    image: centos:8
    pre_build_image: true
  - name: centos7
    image: centos:7
    pre_build_imagr: true
  - name: ubuntu_latest
    image: ubuntu:latest
    pre_build_image: true
provisioner:
  name: ansible
scenarios:
  - name: centos8
    converge_sequence:
      - create
      - converge
      - check
    roles:
      - role: clickhouse2
    variables:
      clickhouse_packages:
        - clickhouse-client
        - clickhouse-server
        - clickhouse-common-static
      clickhouse_version: 23.4.6.25
verifier:
  name: ansible
