---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos7
    image: centos:centos7
    pre_build_image: true
provisioner:
  name: ansible
scenarios:
  name: centos7
test_sequence:
    - destroy
    - create
    - converge
    - destroy
roles:
    - role: clickhouse2
variables:
   clickhouse_packages:
     - clickhouse-client
     - clickhouse-server
     - clickhouse-common-static
   clickhouse_version: 23.4.6.25
verifier:
  name: ansible
