---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos7
    image: centos:centos7
    pre_build_image: true
provisioner:
  name: ansible
test_sequence:
    - destroy
    - create
    - converge
    - destroy
verifier:
  name: ansible
