---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos_7
    image: centos:7
  - name: ubuntu_20.04
    image: ubuntu:20.04
  - name: instance
    image: quay.io/centos/centos:stream8
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
