---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu_latest
    image: ubuntu:latest
    pre_build_image: true
    ansible_python_interpreter: /usr/bin/python3.8
provisioner:
  name: ansible
  ansible_ver: "2.10"
scenario:
  name: ubuntu_latest
roles:
  role: vector1
variables:
  vector_version: 0.32.1-1
verifier:
  name: ansible
