---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos
    image: centos:8
    pre_build_image: true
provisioner:
  name: ansible
  ansible_ver: ">=2.10,<2.12"
scenario:
  name: centos8
  test_sequence:
    - destroy
    - create
    - converge
    - destroy
roles:
   - role:vector1
variables:
   vector_version: 0.32.1-1
verifier:
  name: ansible
