---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos8
    image: centos:8
    pre_build_image: true
provisioner:
  name: ansible
  ansible_ver: "2.10"
scenario:
  name: centos8
  test_sequence:
    - destroy
    - create
    - converge
    - destroy
verifier:
  name: ansible
